services:
  app:
    build:
      context: ./api
    platform: linux/amd64
    ports:
      - 3000:3000
    command:
      - /bin/bash
      - -c
      - |
        apt update && apt -y install expat && exec uvicorn app.main:app --host=0.0.0.0 --port=3000 --reload --reload-dir /api
    volumes:
      - ./api:/api
    working_dir: /api
    depends_on:
      postgis:
        condition: service_healthy
  ui:
    image: node:20-bullseye-slim
    ports:
      - 5173:5173
    command:
      - /bin/bash
      - -c
      - |
        npm install && npm run dev -- --host
    volumes:
      - ./ui/:/app
    working_dir: /app
  postgis:
    image: kartoza/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=poi_satellite_app
    ports:
      - 5433:5432
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./postgis-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=postgres --dbname=poi_satellite_app --host=postgis --port=5432 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 100
volumes:
  postgis-data:
